server:
  port: 8083
  servlet:
    context-path: /chengredis
    session:
      timeout: 3600 # 单位为秒
      cookie:
        max-age: 3600
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://47.102.43.84:3306/wuhu?serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
      type: com.alibaba.druid.pool.DruidDataSource  # 阿里druid 数据源
  #redis 哨兵模式未开启
  redis:
    database: 0
    host: 47.102.43.84
    port: 6379
    password: 1234
    timeout: 500
    jedis:
      pool:
        max-idle: 8 #池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        min-idle: 0 #目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
        max-active: 8 #池在给定时间可以分配的最大连接数。使用负值无限制。
        max-wait: -1 #连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.chengredis.entity
